const environmental = {
  picture: {
    label: "Upload Your Picture",
    value: [],
    type: "file",
    url: "",
    required: false,
    isAutoFill: false,
    isArea: false,
  },
  organizationScope: {
    label: `What are the organization's Scope 1 and Scope 2 GHG emissions, and, if applicable, Scope 3 emissions?`,
    value: "",
    value2: "",
    value3: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  totalEnergyConsumption: {
    label:
      "What is your total energy consumption, and what percentage is from renewable sources?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  assessManageSupplyChainEnvironmentalImpact: {
    label:
      "How do you assess and manage the environmental impact of your supply chain?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  greenhouseGasEmissionsReductionTargets: {
    label:
      "What are your short and long-term targets for reducing greenhouse gas emissions?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  energyEfficiencyMeasures: {
    label: "Describe any energy efficiency measures and their results.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  climateChangeRiskManagement: {
    label: "How do you manage risks related to climate change?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  waterUsageReductionInitiatives: {
    label:
      "What initiatives are in place for reducing water usage and ensuring sustainable water management?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  hazardousWasteManagementProcess: {
    label:
      "Detail your company's process for hazardous waste management and disposal.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  biodiversityProtectionMeasures: {
    label:
      "What measures are taken to protect and restore biodiversity in areas affected by your operations?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  airNoisePollutionManagement: {
    label: "How do you address air and noise pollution from your operations?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalConservationProjects: {
    label:
      "Describe your company's involvement in environmental conservation projects.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalConsiderationsInProductDesign: {
    label:
      "How are environmental considerations integrated into your product design and development process?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  packagingMinimizationStrategies: {
    label:
      "What strategies are employed for packaging to minimize environmental impact?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  circularEconomyPractices: {
    label: "Describe any circular economy practices your company follows.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  soilContaminationRiskAssessment: {
    label: "How do you assess and address soil contamination risks?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainableResourceUseAndSourcingApproach: {
    label:
      "What is your approach to sustainable resource use and raw material sourcing?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  stakeholderEngagementEnvironmentalPerformance: {
    label:
      "How do you engage with and educate stakeholders about your environmental performance?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  GMOsPolicy: {
    label:
      "What are your policies on the use of genetically modified organisms (GMOs)?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  renewableEnergyProjectsInvolvement: {
    label:
      "Describe any renewable energy projects your company is involved in.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ozoneDepletingSubstancesEmissionsMonitoring: {
    label:
      "How do you monitor and manage emissions of ozone-depleting substances?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  energyStorageConservationStrategies: {
    label: "Detail your strategies for energy storage and conservation.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  carbonOffsettingAndCreditsApproach: {
    label: "What is your approach to carbon offsetting and carbon credits?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalComplianceAcrossRegions: {
    label:
      "How do you ensure environmental compliance across different regions?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  lowCarbonEconomyTransitionStrategy: {
    label: "Describe your strategy for transitioning to a low-carbon economy.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalExpenditureInvestments: {
    label: "What are your environmental expenditure and investments?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  productLifecycleEnvironmentalImpactAssessment: {
    label:
      "How do you assess the lifecycle environmental impact of your products/services?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  logisticsEnvironmentalImpactReductionInitiatives: {
    label:
      "What initiatives do you have in place for reducing the environmental impact of logistics?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  newProjectsEnvironmentalRiskManagement: {
    label: "How do you manage environmental risks in new projects?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  biodiversityImpactAssessments: {
    label: "Describe any biodiversity impact assessments you conduct.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainableWaterSourcesSustainabilityApproach: {
    label:
      "How do you ensure the sustainability of water sources for your operations?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  landUseAndForestConservationPolicies: {
    label: "What are your policies on land use and forest conservation?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  wasteReductionAndRecyclingStrategies: {
    label:
      "Describe your strategies for waste reduction and the promotion of recycling.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  electronicWasteManagementApproach: {
    label: "How do you manage electronic waste?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainableAgriculturePracticesInSupplyChain: {
    label:
      "What is your approach to sustainable agriculture practices in your supply chain?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  stakeholderEngagementEnvironmentalGrievances: {
    label:
      "How do you address environmental grievances from your stakeholders?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalMonitoringTechnologies: {
    label:
      "What technologies do you employ for environmental monitoring and management?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainableFisheriesAndMarineResourceManagement: {
    label:
      "Describe your approach to sustainable fisheries and marine resource management.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  supplyChainEnvironmentalImpactsAssessment: {
    label:
      "How do you assess and mitigate the environmental impacts of your supply chain?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  plasticUseReductionPolicy: {
    label: "What is your policy on plastic use and reduction?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalEducationAndAwarenessContributions: {
    label: "How do you contribute to environmental education and awareness?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalNGOCollaborations: {
    label: "Detail any collaborations with environmental NGOs or initiatives.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
};
const social = {
  picture: {
    label: "Upload Your Picture",
    value: [],
    type: "file",
    url: "",
    required: false,
    isAutoFill: false,
    isArea: false,
  },
  workerHealthSafety: {
    label:
      "How do you ensure worker health and safety, and what performance indicators do you use?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  diversityInclusionPolicies: {
    label:
      "Describe your company's policies and practices on diversity and inclusion.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  employeeMentalHealthSupport: {
    label: "How do you support employee mental health and well-being?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  fairCompensationBenefits: {
    label: "What are your practices for fair compensation and benefits?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ethicalLaborPractices: {
    label:
      "How do you ensure ethical labor practices and prevent forced and child labor in your supply chain?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  employeeTrainingDevelopment: {
    label: "Describe your approach to employee training and development.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  workLifeBalanceSupport: {
    label: "How do you support work-life balance for your employees?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  employeeFeedbackEngagement: {
    label: "What mechanisms are in place for employee feedback and engagement?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  humanRightsIssuesAddressment: {
    label:
      "How do you address human rights issues within your operations and supply chain?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  communityDevelopmentPrograms: {
    label:
      "What community development programs do you participate in or support?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  customerDataPrivacyProtection: {
    label: "How do you ensure the privacy and protection of customer data?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  consumerHealthSafetyInitiatives: {
    label:
      "Describe your initiatives for promoting consumer health and safety.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  localCommunityEngagement: {
    label:
      "How do you engage with local communities to address their concerns and needs?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  discriminationHarassmentPolicies: {
    label:
      "What policies do you have in place to prevent discrimination and harassment?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  economicDevelopmentSupport: {
    label:
      "How do you support the economic development of the communities in which you operate?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  volunteerProgramsCommunityService: {
    label:
      "Describe your volunteer programs and employee involvement in community service.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  socialRisksAssessment: {
    label:
      "How do you assess and manage social risks in new projects or expansions?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  indigenousRightsEngagement: {
    label:
      "What is your approach to indigenous rights and engagement with indigenous communities?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  supplyChainSocialImpactsManagement: {
    label: "How do you address the social impacts of your supply chain?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  educationSkillsDevelopmentContribution: {
    label:
      "Describe your company's contribution to education and skills development.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  productServiceAccessibilityInclusiveness: {
    label:
      "How do you ensure accessibility and inclusiveness of your products/services?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  productSafetyQualityMeasures: {
    label: "What measures do you take to ensure product safety and quality?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  supplierRelationshipsSocialResponsibility: {
    label:
      "How do you manage relationships with suppliers to ensure social responsibility?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  NGOSSocialInitiativesPartnerships: {
    label: "Describe any partnerships with NGOs or social initiatives.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  socialGrievancesAddressment: {
    label:
      "How do you address grievances related to social issues from your stakeholders?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  genderEqualityStanceApproach: {
    label: "What is your stance on and approach to gender equality?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  disabledIndividualsIntegrationSupport: {
    label:
      "How do you support the integration of disabled individuals in the workplace?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  employeeAssociationBargainingPolicy: {
    label:
      "What is your policy on employee freedom of association and collective bargaining?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ethicalSourcingMaterials: {
    label: "How do you ensure the ethical sourcing of materials?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  socialImpactAssessmentsOperations: {
    label:
      "Describe any social impact assessments you conduct for your operations.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  disasterReliefHumanitarianEffortsContribution: {
    label: "How do you contribute to disaster relief and humanitarian efforts?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  culturalHeritagePreservationInitiatives: {
    label:
      "What initiatives do you have for promoting cultural and heritage preservation?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  localInfrastructureImpactManagement: {
    label:
      "How do you address the impact of your operations on local infrastructure and services?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  politicalContributionsLobbyingPolicies: {
    label:
      "What is your stance and policies on political contributions and lobbying?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  fairMarketingAdvertisingPractices: {
    label: "How do you ensure fair marketing and advertising practices?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  customerSatisfactionFeedbackPolicies: {
    label: "Describe your policies on customer satisfaction and feedback.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  environmentalSustainabilitySocialAspectsAddressment: {
    label:
      "How do you address the social aspects of environmental sustainability?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  productServiceDesignInclusivityStrategies: {
    label:
      "What strategies do you employ to ensure inclusivity in your product/service design?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  migrationLocalEmploymentImpactManagement: {
    label:
      "How do you manage the impact of your operations on migration and local employment?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  digitalDividePromotionDigitalLiteracyInitiatives: {
    label:
      "Describe your initiatives to address digital divide and promote digital literacy.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
};
const governance = {
  picture: {
    label: "Upload Your Picture",
    value: [],
    type: "file",
    url: "",
    required: false,
    isAutoFill: false,
    isArea: false,
  },
  sustainabilityGovernanceStructure: {
    label:
      "How is sustainability governance structured within your organization?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  corporateEthicsIntegrityPolicies: {
    label:
      "Describe your policies and practices regarding corporate ethics and integrity.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  internationalStandardsComplianceApproach: {
    label:
      "How do you ensure compliance with international standards and local regulations?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainabilityRiskManagementApproach: {
    label:
      "What is your approach to risk management, especially regarding sustainability risks?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  stakeholderEngagementProcess: {
    label:
      "Describe your stakeholder engagement process and how feedback is incorporated.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainabilityReportingTransparency: {
    label:
      "How do you ensure transparency and accuracy in your sustainability reporting?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  anticorruptionBriberyEthicsPolicies: {
    label:
      "What are your policies on anti-corruption, bribery, and business ethics?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  conflictOfInterestManagementApproach: {
    label: "How do you manage conflicts of interest within your organization?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ESGOversightLeadershipBoardStructure: {
    label:
      "Describe your company's leadership and board structure regarding ESG oversight.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  accountabilityEthicalBehaviorMechanisms: {
    label:
      "How do you ensure accountability and ethical behavior at all levels of the organization?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  whistleblowerProtectionEthicalReporting: {
    label:
      "What mechanisms are in place for whistleblower protection and ethical reporting?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  lobbyingActivitiesImpactManagement: {
    label:
      "How do you assess and manage the impact of your lobbying activities?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  shareholderRightsEngagementPolicies: {
    label:
      "Describe your policies and practices on shareholder rights and engagement.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  dataSecurityCyberThreatProtectionApproach: {
    label:
      "How do you ensure data security and protection against cyber threats?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  supplyChainGovernanceManagementApproach: {
    label: "What is your approach to managing supply chain governance?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  legalRegulatoryComplianceApproach: {
    label:
      "How do you address legal and regulatory compliance across different jurisdictions?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ESGTrainingBoardManagement: {
    label:
      "Describe any ESG-related training provided to your board and management.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  governancePracticesPerformanceMonitoring: {
    label:
      "How do you monitor and evaluate the performance of your governance practices?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  executiveCompensationSustainabilityAlignmentPolicy: {
    label:
      "What is your policy on executive compensation and alignment with sustainability goals?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  mergersAcquisitionsDivestituresSustainabilityImpactManagement: {
    label:
      "How do you manage the sustainability impacts of mergers, acquisitions, and divestitures?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ESGReportingInternalControlsAuditProcedures: {
    label:
      "Describe your internal controls and audit procedures for ESG reporting.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  boardIndependenceDiversityApproach: {
    label: "How do you ensure the independence and diversity of your board?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  informationDisclosureStakeholderCommunicationPolicies: {
    label:
      "What are your policies on information disclosure and communication with stakeholders?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  politicalContributionsLobbyingActivitiesManagement: {
    label:
      "How do you address and manage political contributions and lobbying activities?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  regulatorEngagementSustainabilityIssuesStrategy: {
    label:
      "Describe your strategy for engaging with regulators on sustainability issues.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ESGIntegrationBusinessStrategyPlanningApproach: {
    label:
      "How do you incorporate ESG considerations into business strategy and planning?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  stakeholderInterestConflictManagementApproach: {
    label:
      "What is your approach to managing conflicts between stakeholder interests?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  intellectualPropertyProtectionSustainabilityPromotionApproach: {
    label:
      "How do you ensure the protection of intellectual property while promoting sustainability?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainabilityTargetsObjectivesSettingReviewProcesses: {
    label:
      "Describe your processes for setting and reviewing sustainability targets and objectives.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  jointVenturesPartnershipsSustainabilityManagement: {
    label:
      "How do you manage the sustainability aspects of joint ventures and partnerships?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainabilityInvestmentDecisionApproach: {
    label: "What is your approach to sustainability in investment decisions?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  governancePracticesEffectivenessAssessment: {
    label: "How do you assess the effectiveness of your governance practices?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainabilityCertificationsStandardsAdherence: {
    label:
      "Describe any sustainability certifications, standards, or frameworks you adhere to.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainabilityRisksOpportunitiesManagementReporting: {
    label:
      "How do you manage and report on sustainability-related risks and opportunities?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  ESGIssueIdentificationPrioritizationApproach: {
    label:
      "What is your approach to ESG issue identification and prioritization?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  supplierEngagementESGIssuesDevelopment: {
    label:
      "How do you ensure the engagement and development of your suppliers on ESG issues?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  sustainableFinanceInvestmentPoliciesPractices: {
    label:
      "Describe your policies and practices on sustainable finance and investment.",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  emergingTechnologiesEthicalConcernsAddressment: {
    label:
      "How do you address ethical concerns related to emerging technologies?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  regulatoryChangesEngagementResponsePractices: {
    label:
      "What are your practices for engaging with and responding to regulatory changes?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
  continuousImprovementESGPerformanceReporting: {
    label:
      "How do you ensure continuous improvement in your ESG performance and reporting?",
    value: "",
    type: "text",
    required: false,
    isAutoFill: true,
    isArea: true,
  },
};

export const ESRS = { environmental, social, governance };
